Repository ipfs-force-community/damocles, pull requests merged in 2022-09, with the labels that each got.

#406 fix(poster): inject right logger
  venus-sector-manager/modules/poster/runner.go
Labels: bug

#397 feat(vsmgr): import mongo store
  docs/en/04.venus-sector-manager-config.md
  docs/zh/04.venus-sector-manager的配置解析.md
  venus-sector-manager/cmd/venus-sector-manager/internal/util.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_kvstore_migrate.go
  venus-sector-manager/dep/sealer.go
  venus-sector-manager/dep/sealer_constructor.go
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
  venus-sector-manager/modules/config.go
  venus-sector-manager/pkg/kvstore/mongo.go
  venus-sector-manager/pkg/kvstore/mongo_test.go
Labels: priority:mid, vsmgr

#413 chore(vsm): fix proof event log
  venus-sector-manager/modules/miner/proof_event.go
Labels: vsmgr

#423 fix(cli): list sector should work when hit one selectors
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
Labels: bug

#436 fix: handle the replace-state of the message
  venus-sector-manager/cmd/venus-sector-manager/internal/global.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_message.go
  venus-sector-manager/modules/impl/commitmgr/commitmgr.go
  venus-sector-manager/modules/impl/sectors/snapup_commit.go
  venus-sector-manager/pkg/messager/api.go
Labels: needs-cherry-pick-0.4

#417 perf(worker): remove some larger log
  venus-worker/src/sealing/worker/task/event.rs
Labels: vc-worker, performance, needs-cherry-pick-0.4

#446 Feat/wc/import sealingduration in deal
  docs/en/04.venus-sector-manager-config.md
  docs/zh/04.venus-sector-manager的配置解析.md
  venus-sector-manager/modules/config.go
  venus-sector-manager/modules/impl/mock/sealer.go
  venus-sector-manager/modules/sealer/sealer.go
Labels: vsmgr
