Repository ipfs-force-community/damocles, pull requests merged in 2022-12, with the labels that each got.

#537 fix(wdpost): safe_call macro keeps the error type of the inner expr
  venus-worker/vc-processors/src/fil_proofs/mod.rs
Labels: needs-cherry-pick-0.4, needs-cherry-pick-0.5

#541 docs: fix typo
  docs/en/03.venus-worker-config.md
  docs/en/04.venus-sector-manager-config.md
Labels: C-docs

#545 opt(vsmgr): cleanup message id if snap up meet error can retry
  venus-sector-manager/modules/impl/sectors/snapup_commit.go
Labels: vsmgr

#546 feat(vsmgr): vsmgr support beneficiary address operation
  venus-sector-manager/cmd/venus-sector-manager/internal/util_miner.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go
Labels: C-cli

#548 fix(vsmgr): fix delete in mongo kv
  venus-sector-manager/pkg/kvstore/mongo.go
  venus-sector-manager/pkg/kvstore/mongo_test.go
Labels: bug

#551 fix(vsmgr): fix cli list sector print last state
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
Labels: C-cli
