Repository ipfs-force-community/damocles, pull requests merged in 2022-10, with the labels that each got.

#459 docs(worker): add docs for rebuild state flow
  docs/en/11.task-status-flow.md
  docs/zh/11.任务状态流转.md
Labels: C-docs

#460 fix: inject *SafeConfig Type
  venus-sector-manager/modules/sealer/sealer.go
Labels: bug

#434 docs: add en readme
  README.md
  docs/images/venus_logo_big2.jpg
Labels: C-docs

#461 docs: remove extra line break
  README.md
Labels: C-docs

#462 docs: README fix wording
  README.md
Labels: C-docs

#463 Docs/0x5459/rebuild docs
  docs/zh/03.venus-worker的配置解析.md
  docs/zh/11.任务状态流转.md
  docs/zh/16.扇区重建的支持.md
Labels: C-docs

#452 feat(vsmgr): implement strict check of check provable
  venus-sector-manager/dep/sealer_constructor.go
  venus-sector-manager/modules/impl/sectors/tracker.go
Labels: vsmgr

#468 fix(worker): disable cc when `enable_deals=false` and `disable_cc=true`
  venus-worker/src/sealing/store/mod.rs
  venus-worker/src/sealing/worker/task/planner/sealer.rs
Labels: bug

#472 fix(vsmgr): challenge should in a proper range
  venus-sector-manager/modules/impl/sectors/tracker.go
Labels: bug

#471 docs: en doc for config file hot reload
  docs/en/03.venus-worker-config.md
  docs/zh/03.venus-worker的配置解析.md
Labels: C-docs

#480 fix(poster): abort should judge on challenge time
  venus-sector-manager/modules/poster/poster_test.go
  venus-sector-manager/modules/poster/scheduler.go
  venus-sector-manager/modules/poster/scheduler_test.go
Labels: bug

#481 Docs/0x5459/improve doc
  docs/en/03.venus-worker-config.md
  docs/zh/03.venus-worker的配置解析.md
  docs/zh/QA.md
Labels: C-docs
