Repository ipfs-force-community/damocles, pull requests merged in 2022-11, with the labels that each got.

#496 feat(vsmgr): add a cmd to declare recover-whole-deadline-faults manually
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_proving.go
Labels: C-cli

#499 feat(vsmgr): update filecoin nv17 rc5
  venus-sector-manager/cmd/venus-sector-manager/internal/blockstore.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
Labels: vsmgr

#500 feat(vsmgr): update filecoin nv17 rc5
  venus-sector-manager/cmd/venus-sector-manager/internal/blockstore.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
Labels: vsmgr

#498 feat(vsmgr): update filecoin nv17 rc5
  venus-sector-manager/cmd/venus-sector-manager/internal/blockstore.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_actor.go
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
Labels: vsmgr

#502 fix(worker): make enable_deals=false work
  venus-worker/src/infra/piecestore/mod.rs
  venus-worker/src/run.rs
  venus-worker/src/sealing/worker/task/planner/common.rs
  venus-worker/src/watchdog.rs
Labels: bug

#509 fix(vsmgr): handle failed msg in termination
  venus-sector-manager/modules/impl/commitmgr/commitmgr.go
Labels: bug

#511 fix(vsmgr): fix empty sector when set sendfund to false in batch prec…
  venus-sector-manager/modules/impl/commitmgr/precommit_processor.go
Labels: bug

#512 fix(vsmgr): fix empty sector when set sendfund to false in batch prec…
  venus-sector-manager/modules/impl/commitmgr/precommit_processor.go
Labels: bug

#513 fix(vsmgr): fix empty sector when set sendfund to false in batch prec…
  venus-sector-manager/modules/impl/commitmgr/precommit_processor.go
Labels: bug

#519 chore(vsmgr): add log in gen wdpost
  venus-sector-manager/modules/poster/poster.go
  venus-sector-manager/modules/poster/runner.go
Labels: vsmgr

#520 feat(vsmgr): keep up with lotus 1.18 & venus 1.8
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
Labels: vsmgr

#522 feat(vsmgr): keep up with lotus 1.18 & venus 1.8
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
Labels: vsmgr, v0.5

#521 feat(vsmgr): keep up with lotus 1.18 & venus 1.8
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
Labels: vsmgr, v0.4

#523 fix(vsmgr): handle failed msg in termination
  venus-sector-manager/modules/impl/commitmgr/commitmgr.go
Labels: vsmgr, v0.4

#525 fix(vsmgr): handle snap up message error code correctly
  venus-sector-manager/modules/impl/sectors/snapup_commit.go
Labels: vsmgr

#527 fix(vsmgr): handle snap up message error code correctly
  venus-sector-manager/modules/impl/sectors/snapup_commit.go
Labels: bug, vsmgr, v0.4

#526 fix(vsmgr): handle snap up message error code correctly
  venus-sector-manager/modules/impl/sectors/snapup_commit.go
Labels: bug, vsmgr, v0.5
