Repository ipfs-force-community/damocles, pull requests merged in 2023-02, with the labels that each got.

#582 feat(vsm: cli): Refactor renew and remove extend
  venus-sector-manager/cmd/venus-sector-manager/internal/util_sealer_sectors.go
Labels: breaking change

#590 opt(vsmgr): no wait on submit wdpost stage
  venus-sector-manager/modules/poster/runner.go
Labels: vsmgr

#616 chore(vsm: cli): make `--net` flag deprecated
  venus-sector-manager/cmd/venus-sector-manager/internal/global.go
  venus-sector-manager/cmd/venus-sector-manager/main.go
Labels: vsmgr, needs-cherry-pick-0.4, needs-cherry-pick-0.5

#614 chore(worker): upgrade crates
  docs/zh/15.venus-worker_PC1_HugeTLB_Pages_支持.md
  venus-worker-util/src/bin/venus-worker-util/sealcalc/csv.rs
  venus-worker-util/src/bin/venus-worker-util/sealcalc/tui.rs
  venus-worker/Cargo.lock
  venus-worker/Cargo.toml
  venus-worker/Makefile
  venus-worker/rust-toolchain
  venus-worker/src/bin/venus-worker/store/hugepage.rs
  venus-worker/src/bin/venus-worker/worker/mod.rs
  venus-worker/src/logging/mod.rs
  venus-worker/src/run.rs
  venus-worker/src/sealing/store/mod.rs
  venus-worker/src/sealing/worker/task/mod.rs
  venus-worker/src/sealing/worker/task/planner/common.rs
  venus-worker/src/sealing/worker/task/planner/mod.rs
  venus-worker/src/sealing/worker/task/planner/rebuild.rs
  venus-worker/src/sealing/worker/task/planner/sealer.rs
  venus-worker/src/sealing/worker/task/planner/snapup.rs
  venus-worker/vc-processors/Cargo.toml
  venus-worker/vc-processors/src/b64serde.rs
  venus-worker/vc-processors/src/builtin/processors/piece/fetcher/http.rs
  venus-worker/vc-processors/src/builtin/processors/transfer/tests.rs
  venus-worker/vc-processors/src/core/ext/producer.rs
  venus-worker/vc-processors/src/fil_proofs/mod.rs
  venus-worker/vc-processors/src/sys/numa.rs
Labels: vc-worker

#619 fix(vsm): `MarshalText` should not return nil and no error
  venus-sector-manager/modules/config_util.go
Labels: vsmgr, needs-cherry-pick-0.4

#623 fix(vsm): upgrade jsonrpc to fix panic
  venus-sector-manager/go.mod
  venus-sector-manager/go.sum
Labels: bug, vsmgr, needs-cherry-pick-0.4, needs-cherry-pick-0.5
