Repository ipfs-force-community/damocles, pull requests merged in 2023-06, with the labels that each got.

#754 fix(worker): obtain the local timezone correctly
  venus-worker/Cargo.toml
  venus-worker/src/logging/mod.rs
Labels: needs-cherry-pick-0.6

#755 feat(vsm): make wdpost logs more detailed
  venus-sector-manager/modules/poster/runner.go
Labels: needs-cherry-pick-0.6

#756 Fix/set delay when snaup confict with deadline
  venus-sector-manager/modules/impl/sectors/snapup_commit.go
Labels: needs-cherry-pick-0.6

#778 Update README.md
  README.md
Labels: C-docs

#779 Update README.md
  README.md
Labels: C-docs

#789 fix: check deadline is mutable
  damocles-manager/modules/impl/sectors/snapup_commit.go
  damocles-manager/modules/impl/sectors/snapup_commit_test.go
Labels: bug, needs-cherry-pick-0.6, damocles-manager, needs-cherry-pick-0.7
